apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage
resources:
  - service.yaml
  - deployment.yaml
  - ingress.yaml
  - ts-ingress.yaml
  - configmap.yaml
  - role-binding.yaml
  - service-account.yaml
  - sa-secret.yaml
