apiVersion: v1
kind: ConfigMap
metadata:
  name: qbitt-cm
  namespace: arr-stack
data:
  PUID: "1000"
  PGID: "1000"
  UMASK: "002"
  TZ: "America/New_York"
  WEBUI_PORTS: "8080/tcp"

  VPN_ENABLED: "true"
  VPN_CONF: "wg0"
  VPN_PROVIDER: "proton"
  VPN_AUTO_PORT_FORWARD: "true"
  VPN_LAN_LEAK_ENABLED: "false"
  VPN_LAN_NETWORK: "192.168.8.0/24,10.42.0.0/24"

  VPN_HEALTHCHECK_ENABLED: "true"
  PRIVOXY_ENABLED: "false"
  UNBOUND_ENABLED: "false"

