apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: arr-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      nodeSelector:
        kubernetes.io/hostname: optiplex
      containers:
        - name: qbittorrent
          image: ghcr.io/hotio/qbittorrent
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          envFrom:
            - configMapRef:
              name: qbittorrent-config
          ports:
            - containerPort: 8080
              protocol: TCP
              name: webui

          volumeMounts:
            - name: qbittorrent-config
              mountPath: /config
            - name: qbittorrent-downloads
              mountPath: /data/torrents
              subPath: torrents
      volumes:
        - name: qbittorrent-config
          persistentVolumeClaim:
            claimName: qbittorrent-config-pvc
        - name: qbittorrent-downloads
          persistentVolumeClaim:
            claimName: data-pvc
