apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: arr-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      nodeSelector:
        kubernetes.io/hostname: optiplex
      containers:
        - name: qbittorrent
          image: ghcr.io/hotio/qbittorrent:latest
          envFrom:
            - configMapRef:
                name: qbitt-cm
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          ports:
            - containerPort: 8080
              protocol: TCP
              name: webui

          volumeMounts:
            - name: qbittorrent-config
              mountPath: /config
            - name: qbittorrent-downloads
              mountPath: /data/torrents
              subPath: torrents
            - name: qbittorrent-vpn
              mountPath: /config/wireguard/wg0.conf
              subPath: wg0.conf
              readOnly: true
      volumes:
        - name: qbittorrent-config
          persistentVolumeClaim:
            claimName: qbittorrent-config-pvc
        - name: qbittorrent-downloads
          persistentVolumeClaim:
            claimName: data-pvc
        - name: qbittorrent-vpn
          secret:
            secretName: qbitt-vpn-secret
