---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-auth
  namespace: picture-it
spec:
  encryptedData:
    REDIS_PASSWORD: AgB/nd3BaT3D6zdjwqrIgLgIOy8O3hyyvIo2KAJAo/1idw3JxMCUmdCibnxH+0wGU2JHBhrkPN+0ulP2lo7tVoduEwZ4MDWQSQ87k0znzd5RKErc3DGyacN0LoyAZEM8MnAO3/RedptMPWzd3e1Lbx4ndLb7hGr6pT9hmurqUGf0D4h6vQwEUGR6tB44XgFr8iDBviy+iTINIevbmwpbPNXtxvUBakEtgTEayRNvi5abTVBV+b/ChWjrB/Yz2sMAEUdZSKor3TTOwet+YGYXnYBeizbMITb4ayn6+efKw2PbpIb0luHjutta2VbVoU94lNhqeYKuFiRtaSmHmiJFuQfF2pFxf45xg4TfY1klDoGUtG1Q0aaw/IRS163bHbFBIhDIZ1MKyzEDdmvhkoqo7WFH4NoFRSX8+zkI6XX07z+CHCWlrkondJ1JA+1N5jVkVOfR4PeqLHmPDBWbJNDiRavXPxj/f01AdTpgcsbr/Viw4CBdWpFnVZ1MquRouoyBnujsypenndAvoBTa/Znao93OD1kK8YrJP7fwkJ/dxpFn/24d7hAIHAziMtchRgV7ZuzgnuY0bOKoyNVARXfW1ijLYE5C4POlLLJTVD+KRLRlOUku4QBKt0W7Tnyh66cr3niEH1IX5Nkgq3eEMDKwS2reFx/+zfwLnqkITyZ9Ee2bDSK5K4BVrHGhjq+CKX8fMjxSFTt5zw==
  template:
    metadata:
      name: redis-auth
      namespace: picture-it
    type: Opaque
