---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: palworld-secrets
  namespace: palworld
spec:
  encryptedData:
    adminPassword: AgA91cxF0r9N7mTzaOnZ+M+vjSjCczIBqPyWC3DWbwb2k9CrqBLiONHrOh4qAmo4ZSG45BQWvFG/MaXHbJ37u/Mtey+Sdui93RzH5LH7msCuLwQpr0Km2j8I1iGkfcynU8Ioxd5D7uvq7W/H0s0i3Xe0W0yWkXPeumnAL65b2qd9G2o9Vg+9lzrlvfqTq3+8cEPmHfNHX2MHOS9Ae0T7LG9aScc19mItqJGzRi7GsVy3w4dAfjUPRPeoWwvYoCYPSavMmOGW24x997Vt2r+227Ot6kn7miULGpCZyFVW3i7aexnvfceY6A4mQmvLze2g7apVzvvyF64AVuHotpZ0FDBsOfc9IcElnxiHsFyhVpoesZcIW0WGoX5O8FWxXiehCgeeeleyula1FFqu4+s7hqaThFCkE3/h6DQWEYuq3uyw3AIB9Eiw8bZr4m2er8sTvOY3Hh/3wDF4/HrdfJzkKjnJTD+h1CNniouuBbEeH7zXFgmLNTJEv3ZVyGLjOF58xIJbo3gYyeybn58BWiJ3qN9VsMF0nj70vT8gsjbhqj/bToCZvNREWx8i0sSF3FEnJ+OiANOe0XGBTkxwtZhvD6taXdfAcd+BdDDK/yicOfVK+HCB4noUF/PZyFQRatPf1Fm7Gk1gfD1RYhXHnSQ3ZGMKg9HujqIt7UUlxS8QKxThttqQEnOUypr56+jG8WhKMF4hWEnq4Q==
    serverPassword: AgAKErA129AI/xFU0GEibhWE3CaxTAuThI240IZtrUznsOjhm4RMjJDJ+ouJOzadEs9850dt5ZeUGgveLAHLtD8baFt+Lz9N5kyR5v959+uYx6h92snQZEDXSGmqNlHqbVu+vCcIEEUAcr4VGJ8V7kRErBGEiu/CnXk07kE/jx9Fr02Uc+vCY3PHnhRheD1m2ewJFN3H8SebzP9jdUi5H4aSLTWnrJ2s3pay03XDc1lM0xYnlK0pzG26rJRNTVpIkB8nPTpUqeZs6P/sha1n+Wszwwvpfa7zMOFkobRS2b/U+xzR+EwoOYQKJGFe8C1tEOzAFt559k5Ksl4fK2faHTdHCjDZQ2fkIjqnsj/Krwa2ifNcVNvJeTWkQ42r48SPhuxPjZGjL0nuHfYmDx1n0d0zHD80EbeLh8/0JHfx7mXH8qKpgENP0GERQ/VFgZFwlpEne3VQVtheo2O1pdMUMa0zKdYv1++VnYgr+coNt60ZQK7TnC1q1Vns4oRWbgl50jL9pepNCDF+bsc/zcRZ9UY875+4To1d403lrtqHaAxkGO4snYoAKig3iz4KJIoWSi4plw8vSyzlWEGRXOCdM6ZOnxQWpzegBCKqSu5iGgfmJ/qNhgyO7Uy9ixAQT9+5pj77ciNSYwlfeqZpEFk7gdg7ljgIUBcXm91v/7+O8lbk3jDLaMGYZP+VxIcZvrzH7qayNc+uaUECtg==
  template:
    metadata:
      name: palworld-secrets
      namespace: palworld
    type: Opaque
