apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: picture-it
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/MichaelLutz1/mlutz-infra.git
    targetRevision: main
    path: apps/picture-it/base

  destination:
    server: https://kubernetes.default.svc
    namespace: picture-it

  syncPolicy: null
