apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: ghcr.io/prometheus-community/charts
      chart: kube-prometheus-stack
      targetRevision: 83.6.0
      helm:
        releaseName: prometheus
        valueFiles:
          - $values/apps/prometheus/helm/values.yaml
    - repoURL: https://github.com/MichaelLutz1/mlutz-infra.git
      targetRevision: main
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: prometheus
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
