apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: ghcr.io/prometheus-community/charts
    targetRevision: 83.6.0
    helm:
      releaseName: prometheus
  destination:
    server: "https://kubernetes.default.svc"
    namespace: prometheus
