apiVersion: apps/v1
kind: Deployment
metadata:
  name: picture-it-deployment
  labels:
    app: picture-it
spec:
  replicas: 3
  selector:
    matchLabels:
      app: picture-it
  template:
    metadata:
      labels:
        app: picture-it
    spec:
      containers:
      - name: picture-it
        image: mlutzy/picture-it:latest
        ports:
        - containerPort: 80
