---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgBlPwWBdFavs7TpuyXHD6MVuI5fg9X+JOWIx2Mj1r+ZaXlev3egijERzsK2LZfutdKii0l9LTaT46Ond2ZqJTAzeISBDn6lCc0sA89+G4OmkWhh1IORZlrQ/33qhj3+cR24HBswDKFVgeaL/8Lozlh3cDgD0kxqW1a7/repMyN2AakS5uUNi8wf+2q127bFUOWsCfAtFoFoYTYsP9NKomRbUPpwHHXPEMaY1iPZJhWLFgDSnPuCEJZAjyvYY1NCJucCKGocGetf/dOm8lqm1hpdifOutN50i9s9MTcYEDiIYLA4rUAE/ZlJIL7h0HFBz+Kg0w4Uob4ElxlNUw7Bq4ASda144cyF7d05qVKjx461pIVUSfar9dehZ0YNHFwnEQFsOLVcuGa00KiJXt2OtbUedYjySb16Bi2hQadW7cGMK9IVKnkN/nWCnMo+oWIkLw6g+QZuPcp5IaNbyliJCy9nriC9d5a0slU1wqC3IjjB127WOp4drGn1x/t4HYt3VAa6UYt9YIAEP6oDbdGJ/T5O1UgNpctW1TFxu0HZib7q7RCcJ68fBaNGrF3szbL32Wyd9xOdQDkv48s2Ex4t8JKoFiaUMANSqMUFhKukFXUELuIan3sZDU9o/EJNFUK6gzODlxWqTG9rq/FyDoWpekCSWiCNIbeds2jpcLW5TzOnLtwfPU8JqW+VDL/O9bjvhr2/cIuzUH7ULMF+MkvCkFzWl/MVvL0aniIcU+EnrBhc0xZkGsoEJ7Ho5RTJvVhyW6SPPRRM1JHLAD04142xKUY/6NDUE8Sxp6LkA2HiPTFr0QzqA9E4ZtRtcuxGylHc23YWOn8QDCF/MNy3zGMfdnvxgdusgrlUyvI4uTQSnThQYfmbIdJsw0oEGV/BFfqNvpl4TY7ZMmWwm0+NVoDkoxaPDQ1bBujWlB7eposhsRXqgjOdNmDFATKk
  template:
    metadata:
      name: tunnel-token
      namespace: cloudflared
