---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    clientId: AgCRADEnklOSTU3heI+meIiah1TwQg4d4wHPg+lk2nTP8KMKttyi3Yzt7dTUCtCcGoKGp8Qs9jsREWn7v8fs3vvcu1HpDru1RtaKIWz7mvBDidZ0PcAoTQHn4zfo0xAvu0K6MBg/fx6cogf7YjMltFmqbh2hTWvOZRyjaP7luSbPxJGGp3XXP0RQg92hkXW4M4yGuyV0u8/eipZTyYD0vfR3+JeFvhG2lVws4HnzgKnuHlQxdq+QZhHdyEhEulGcO7LjJY2WcqqPK4P3e3KPw1F/YeHNL6Ai9YCB/mUGh+oVxhLHsAE6TC/6Ele3Np2fTv2vegqN+e4ISsPWnmLkfBa0zjlXoqQCI+Use0CZhxiRWNY/l5bwfivJGzB0f1ip+qVg8Yw0ulaPMLJyfuYJUP8OTXM47BInC3Xc9GV3Mzoo5bW76uKcdA59ShMm+nqx3sPMl7Gkv2WU/G4ZIGDS/kcaehipCoJj5f4s0uslz28qzRm1wR7nmQqrr1nQNZaRkDWyMjaZRLOqLMJT/3ixRgsN+GR1Vi0/MRiiG+J3R9NelTS8mNkNsephxG4gE6725xds9GAkLqOTe8Tuau6JeOT1GxqsdQqhhs1dMFBqESh9bUniIiLIQUe+o/WbN6f/quQP2Vj2nu+hO1U7Itb95dxui1iaRs5gnqE2nty/eITBSjo5XSjhmDdl1WyTKe0x/TvTyPlw4PDI6jkGzbPzYmLgKw==
    clientSecret: AgAtiJwq/2o6DWsAUUlBC5lfeSTMfZWkaadGR1dUqeIW+0Uo+/+hc3Qz9j6KR821NRnyYC0Fk36fjmfoA0JahcpKDi1ZvrDByXrdnr1BGz8JPaCB4e3b2yxGb4HHRiozABIcSq2gdIRJ05pbpRy89KmACHLW1a4fm59mcEEJPp+uefDM+Z+tFQWvgEj0zYZJnUxEbLYPVnfYYm0QBsZebPAzQe/hcN8VQzp6UXYvKm4jj50UnYzAlul4noopuYhjxNVzsDg/MGk6vH/bbhuQsWH0qiBhtdEgVdhlg7Y623bVJUwQGseCu+KPm/6GQuJ+W/klhjucVciMd7/8biME4zp8HstaD3TeNd1O9aqVulos4E1es5K6E8IXWKKqCIhEuPv4TnsP3imwnKT/vPN1V7TkX7wCETTvTijkXa7NyVpcby56WC8oF3kxWY+hrj5+TJ737Lej5USiyz554SGFHPG6Re6HR1+v21U5QwQJfLx/A8Rnhdror4rAt+tGX9m/qhIim0ywYfx5ylXSCNB4yyjmmnQWrxuEovQmGTliwaOFqKCF5fc8xBJ7N22xTktSJ1khTjmPBO9J+DDhylgv07CbQsGn2EkScRmUsCdYuuMSbBPrsg2sueUQpsncmWNmV+836bK8HM7rcx++93aHuq6kw9cyX61Z43cXCkuBZusP5HVwV763Rq41Q0c1Z+ohHKaVAhU19YVaZjdle6yHUiXIm2Gip4TUldEgotEjIQDAkUavsVjLMR93Ll30H7ioFCd0Czm54XFj5wnZMy+6VH7F
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
