---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgAJSoBNbMv2sP7ZCEpCSjMhUsBTtWhtJ6LSo3ZbdYng4uAfcbOEFKSE95SsHUE7xAxrAgMuF/EI/qCZED+lLHCesdEnISuDLgDVIGaqTvJOl2Q5NtGhDgq9RZPCTIoKUjR4R2OL8cHJYjacHeQfKgJHmYIAFjU3RErdz4N/HuVIo4Da28ZMumj3r9qbweAGkEADLJPNcsLt1WloK7SxbQkeIG43OT5cdIrBernCaxiITpMRhtLvWXVAq/4a3jCsjs8XOfB9teJCax90oRANbI09LPrmOryCvf/i54oOMb0IgMkvI0RsYfai2i0Xp+cbeKs9sTtaj/i2dk4pM40VBHMehbZfIDBci6K7UFgYY1HIzs3xui2pHJT4j7COE0lsC+DTntYsOGOATJoj31j5DIFrrNcrNB271YcASLWR+7zqD64JTpzb6sTWVvb2WOtjuOS1bkzcqXaBza3a5DRbmrcBP/HEmOnaSnE5Ont2C7S7uQGVpLsxs6k9LZGZI9rDnzziP08m6FIloMuk491IuvSqcZw0KtPORtwKXCUqvbtV9YPMgtmaGgzDSEtX28Np+78C2PwZipe3GsyGMbAmPByqGTPAw2UCm5M4pXj31A3EhpUXbzXAMO3hNOnFMfxzI/TCyyJadXeaMIfM4gLdquKVjQ4Llegipdo6H38/HPpCPn/1DD0Gx5QeS9azKN4NxPTGowgd/UkKfUoAetuMqFlvbQ==
    client_secret: AgCDb/qjI+ClIcQNSWYDu3Ia8xwcb7L0wiAdFPVCNMjIjXrEeA6qfoOS0r+Sf6fpzRS1147M1elsS12+sbJrizz1H2ODsba4Faup9/fGMDkF7zOTIqpBOXvRwrqRmfCBoNLMJRbh49HxAuWxdR4UKmLlcoQD1zTxIY7FxYWrvpUD/AFMSQubdMQkpw1iRZACrpdOHiy8o135sdk/XEX+45NMBJxXHtQP6ZpvSpGtdKagWXEb9xu9dzRgIjwmBlOcD7C+pNCIDoBQ7QHmwS4jtr9YCg1hsBWUg6tmYn0kh2/Ds4gPUcMV4MFXHTp+8/AxDWZMLpgZXLqy8FYRb+9VLIDPsJS8GFnWcrs9TxT+U99+pWunIQ38lmO4zwyMeawj5YLEVCqN+AdjwwEFOgRS7aKlCg+2Pg2zMcOXTN2ZuWrbAgaDbP4Fbc/q78EogyIhNHMlVEXbg2zh1mE/Io8ag4F4NvS2ixUE4yrUEkzIiGFzMLQso+DTFfCYa4gaAB16cb76gH9uHl5XCnm+8draFkSpfj30UprA1hhlwP+iITmA84HcYJUajmOEWg7LYuFJ832L5VOqax3UrPLHysx1LQLVaIEy0dbR/8F538aS/TbDC5jk1XwhEkAIFbpBmGm5cHS4IkPIxRUvbrn8O7N5v+bbuxJ2jVsaXaaWwp07hQ30OPIV8KWLBtMGNQqGEJHK0V+3yUZNiyqS4+OWhuAzjSI450B068oiB+TGGw11M9dVZ6RdvHX7Ds0CBVpPgksqmMSjAfgYSfhg4U2d9fJ4DBjr
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
