apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-lan
  namespace: argocd
  annotations:
    gethomepage.dev/description: CI/CD UI
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Cluster Management
    gethomepage.dev/icon: argo-cd.png
    gethomepage.dev/name: ArgoCD
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=argocd-server"
spec:
  ingressClassName: traefik
  rules:
    - host: argocd.home.arpa
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
